-- SET ROLE sanya;

DROP TABLE IF EXISTS services CASCADE;
DROP TABLE IF EXISTS personal CASCADE;
DROP TABLE IF EXISTS personal_service CASCADE;
DROP TABLE IF EXISTS saunas CASCADE;
DROP TABLE IF EXISTS sauna_service CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS order_services CASCADE;
